# inspiration from
# - https://linoxide.com/monitoring-2/install-nagios-4-debian-9/

# add user and group
- name: add nagios command group
  group:
    name: nagcmd
    state: present

- name: add nahios user
  user:
    name: nagios
    shell: /bin/nologin
    groups: nagcmd

# install packages
- name: install apache webserver
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apache2
    - apache2-utils
    - php

- name: put www-data in nagcmd group
  user:
    name: www-data
    groups: nagcmd
    append: yes

- name: install general tools
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - wget
    - unzip
    - python-passlib

- name: install built environment
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - autoconf
    - gcc
    - libc6
    - make
    - libgd2-xpm-dev

- name: "create local cache dir ({{local_cache_dir}})"
  connection: local
  become: no
  file:
    state: directory
    path: "{{ local_cache_dir }}"

- name: download tarball
  connection: local
  become: no
  get_url:
    url: https://github.com/NagiosEnterprises/nagioscore/archive/{{nagios_tgz_filename}}
    dest: "{{ local_cache_dir }}/{{ nagios_tgz_filename }}"

- name: create nagios dir
  file:
    state: directory
    path: "{{ nagios_opt_dir }}"

- name: "Extract into {{nagios_tgz_filename}} to {{ nagios_dir }}"
  unarchive:
    src:  "{{ local_cache_dir }}/{{ nagios_tgz_filename }}"
    dest: "{{ nagios_opt_dir }}"

- name: run configure
  command: "./configure --with-nagios-group=nagios --with-command-group=nagcmd --with-httpd_conf=/etc/apache2/sites-enabled/"
  args:
    chdir: "{{nagios_core_dir}}"

- name: run make all
  command: "make all"
  args:
    chdir: "{{nagios_core_dir}}"

- name: run make install
  command: "make install"
  args:
    chdir: "{{nagios_core_dir}}"

- name: run make install-init
  command: "make install-init"
  args:
    chdir: "{{nagios_core_dir}}"

- name: run make install-commandmode
  command: "make install-commandmode"
  args:
    chdir: "{{nagios_core_dir}}"

- name: run make install-config
  command: "make install-config"
  args:
    chdir: "{{nagios_core_dir}}"

- name: run make install-webconf
  command: "make install-webconf"
  args:
    chdir: "{{nagios_core_dir}}"

- name: enable modules in apache
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - rewrite
    - cgi
  notify: apache2 restart

- name: setup password for nagios admin
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: nagiosadmin
    password: "{{nagios_admin_pass}}"
    owner: root
    group: www-data
    mode: 0640
  notify: apache2 restart
