# add user and group
- name: add nagios command group
  group:
    name: nagcmd
    state: present

- name: add nagios user
  user:
    name: nagios
    shell: /bin/nologin
    groups: nagcmd

# install packages
- name: install apache webserver
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apache2
    - apache2-utils
    - php

- name: enable modules in apache
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - rewrite
    - cgi
  notify: apache2 restart

- name: put www-data in nagcmd group
  user:
    name: www-data
    groups: nagcmd
    append: yes

- name: install general tools
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - wget
    - unzip
    - python-passlib

- name: "create local cache dir ({{local_cache_dir}})"
  connection: local
  become: no
  file:
    state: directory
    path: "{{ local_cache_dir }}"

- name: create nagios dir
  file:
    state: directory
    path: "{{ nagios_opt_dir }}"
