# inspiration from
# - https://linoxide.com/monitoring-2/install-nagios-4-debian-9/

- name: install built environment
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - autoconf
    - gcc
    - libc6
    - make
    - libgd-dev

- name: download tarball
  connection: local
  become: no
  get_url:
    url: https://github.com/NagiosEnterprises/nagioscore/archive/{{nagios_tgz_filename}}
    dest: "{{ local_cache_dir }}/{{ nagios_tgz_filename }}"

- name: Extract into {{ nagios_tgz_filename }} to {{ nagios_opt_dir }}
  unarchive:
    src:  "{{ local_cache_dir }}/{{ nagios_tgz_filename }}"
    dest: "{{ nagios_opt_dir }}"

- name: run configure
  command: "./configure --with-nagios-group=nagios --with-command-group=nagcmd --with-httpd_conf=/etc/apache2/sites-enabled/"
  args:
    chdir: "{{nagios_core_dir}}"

- name: run make all
  command: "make all"
  args:
    chdir: "{{nagios_core_dir}}"

- name: run make install
  command: "make install"
  args:
    chdir: "{{nagios_core_dir}}"

- name: run make install-init
  command: "make install-init"
  args:
    chdir: "{{nagios_core_dir}}"

- name: run make install-commandmode
  command: "make install-commandmode"
  args:
    chdir: "{{nagios_core_dir}}"

- name: run make install-config
  command: "make install-config"
  args:
    chdir: "{{nagios_core_dir}}"

- name: run make install-webconf
  command: "make install-webconf"
  args:
    chdir: "{{nagios_core_dir}}"

- name: setup password for nagios admin
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: nagiosadmin
    password: "{{nagios_admin_pass}}"
    owner: root
    group: www-data
    mode: 0640
  notify: apache2 restart

- name: enable nagios as service
  systemd:
    name: nagios
    enabled: yes
