# inspiration from
# - https://linoxide.com/monitoring-2/install-nagios-4-debian-9/

- name: install built environment
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - autoconf
    - gcc
    - libc6
    - make
    - libgd-dev

- name: download tarball
  connection: local
  become: no
  get_url:
    url: https://github.com/NagiosEnterprises/nagioscore/archive/{{nagios_tgz_filename}}
    dest: "{{ local_cache_dir }}/{{ nagios_tgz_filename }}"

- name: calculate hash
  connection: local
  become: no
  stat:
    path: "{{ local_cache_dir }}/{{ nagios_tgz_filename }}"
    checksum: sha256
  register: nagios_core_stat

- name: store checksum
  template:
    src: checksum.txt.j2
    dest: "{{ nagios_opt_dir }}/nagios_core_checksum.txt"
  vars:
      checksum: "{{nagios_core_stat.stat.checksum}}"
  register: nagios_core_checksum_file

# ignore errors in check mode, since --check will otherwise fail at first run
- name: Extract into {{ nagios_tgz_filename }} to {{ nagios_opt_dir }}
  unarchive:
    src:  "{{ local_cache_dir }}/{{ nagios_tgz_filename }}"
    dest: "{{ nagios_opt_dir }}"
  register: core_extract
  when: nagios_core_checksum_file.changed
  ignore_errors: "{{ ansible_check_mode }}"

- name: run configure
  command: "./configure --with-nagios-group=nagios --with-command-group=nagcmd --with-httpd_conf=/etc/apache2/sites-enabled/"
  args:
    chdir: "{{nagios_core_dir}}"
  when: nagios_core_checksum_file.changed or core_extract.changed

- name: run make all
  command: "make all"
  args:
    chdir: "{{nagios_core_dir}}"
  when: nagios_core_checksum_file.changed or core_extract.changed

- name: run make install
  command: "make install"
  args:
    chdir: "{{nagios_core_dir}}"
  when: nagios_core_checksum_file.changed or core_extract.changed

- name: run make install-init
  command: "make install-init"
  args:
    chdir: "{{nagios_core_dir}}"
  when: nagios_core_checksum_file.changed or core_extract.changed

- name: run make install-commandmode
  command: "make install-commandmode"
  args:
    chdir: "{{nagios_core_dir}}"
  when: nagios_core_checksum_file.changed or core_extract.changed

- name: run make install-config
  command: "make install-config"
  args:
    chdir: "{{nagios_core_dir}}"
  when: nagios_core_checksum_file.changed or core_extract.changed

- name: run make install-webconf
  command: "make install-webconf"
  args:
    chdir: "{{nagios_core_dir}}"
  when: nagios_core_checksum_file.changed or  core_extract.changed

- name: setup password for nagios admin
  htpasswd:
    path: "{{nagios_base_dir}}/etc/htpasswd.users"
    name: "{{nagios_admin_user}}"
    password: "{{nagios_admin_pass}}"
    owner: root
    group: www-data
    mode: 0640
  notify: nagios apache2 restart
  ignore_errors: "{{ ansible_check_mode }}"

- name: create nagios config file
  template:
    src: nagios.cfg.j2
    dest: "{{nagios_base_dir}}/etc/nagios.cfg"
    group: nagios
    owner: nagios
    mode: 0664
  notify: reload nagios

- name: enable nagios as service
  systemd:
    name: nagios
    enabled: yes
