- name: create directory for tests
  file:
    path: "{{nagios_tests_dir}}"
    state: directory
    mode: 0775
    owner: nagios
    group: nagios

- name: add contacts
  template:
    src: contacts.cfg.j2
    dest: "{{nagios_tests_dir}}/contacts.cfg"
    group: nagios
    owner: nagios
    mode: 0664
  notify: reload nagios

- name: add hosts
  template:
    src: host_list.cfg.j2
    dest: "{{nagios_tests_dir}}/hosts.cfg"
    group: nagios
    owner: nagios
    mode: 0664
  notify: reload nagios

- name: ensure original localhost checks are removed
  file:
    path: "{{nagios_base_dir}}/etc/objects/localhost.cfg"
    state: absent
  when: nagios_localhost_check
  notify: reload nagios
  
- name: add localhost checks
  template:
    src: localhost_checks.cfg.j2
    dest: "{{nagios_tests_dir}}/localhost.cfg"
    group: nagios
    owner: nagios
    mode: 0664
  when: nagios_localhost_check
  notify: reload nagios
