# nothing yet
- name: nagios apache2 restart
  service: state=restarted name=apache2

- name: check nagios config
  shell: "{{nagios_base_dir}}/bin/nagios -v {{nagios_base_dir}}/etc/nagios.cfg"
  listen: reload nagios

- name: do nagios reload
  systemd: name=nagios state=restarted daemon_reload=yes
  listen: reload nagios
