- hosts: srv-mon
  become: true
  gather_facts: false

  pre_tasks:
  - name: update apt if applicable
    apt:
      update_cache: yes
      cache_valid_time: 3600
    changed_when: False

  - name: set hostname
    hostname:
      name: "{{ inventory_hostname }}"
    tags: pre-tasks

  roles:
  - { role: server-nagios }
